.Dd January 28, 2026
.Dt COPYFILE 1
.Os

.Sh NAME
.Nm copyfile
.Nd copy a file to the clipboard

.Sh SYNOPSIS
.Nm
.Op Pa environment
.Pa filename

.Sh DESCRIPTION
The
.Nm
tool copies a file to the clipboard as a singular line.
.Nm
allows for other files to be included recursively.

.Sh OPTIONS
.Bl -tag -width x
.It Op Pa environment
A JSON file to be used as the environment.
The JSON file must only contain objects with string values.
On macOS 12.0 or newer, JSON5 is used.
.It Pa filename
A UTF-8 encoded file to be copied.
.El

.Sh EXIT STATUS
If
.Nm
can find
.Ar filename ,
it exits with status code 0.

.Sh FILE STRUCTURE
.Nm
supports variable substitution.
Variables can be substituted using the variable operator
.Pq Sy "#\(dq\(dq"
and the value will be fetched from the environment.
.Li #"example"
will be replaced with the value of
.Li example
specified by the environment.
If the value does not exist, an empty value is returned instead.

.Nm
has two ways to include another file.
Using the inclusion operator
.Pq Sy #!
and the environmental inclusion operator
.Pq Sy #!"" .

The inclusion operator
.Pq Sy "#!"
includes the file path that follows relative to the file that includes it.
.Li #!./README.md
will include the file
.Li ./README.md .
If the first two bytes of a file are the inclusion operator, that line is skipped.
If another file needs to be included immediately, preceding it with an empty variable
.Pq Sy #""
will allow that.

The environmental inclusion operator
.Pq Sy #!""
includes the file the variable is set to.
.Li #!"example"
will include the file specified by the value of
.Li example .
If
.Li example
is set to
.Li README.md
then
.Li #!"example"
will include the file
.Li README.md .
.Em NOTE:
Environmental inclusions are relative to
.Pa filename .

.Sh AUTHORS
.An Harry N
