.Dd November 2, 2025
.Dt COPYFILE 1
.Os

.Sh NAME
.Nm copyfile
.Nd copy a file to the clipboard

.Sh SYNOPSIS
.Nm
.Op Pa environment
.Pa filename

.Sh DESCRIPTION
The
.Nm
tool copies a file to the clipboard as a singular line.
.Nm
allows for other files to be included recursively.

.Sh OPTIONS
.Bl -tag -width x
.It Op Pa environment
A JSON file to be used as the environment.
The JSON file must only contain objects with either string or number values.

.Em NOTE:
On macOS 12.0 or newer, JSON5 is used.
.It Pa filename
A UTF-8 encoded file to be copied.
.El

.Sh EXIT STATUS
If
.Nm
is able to read the file specified, it exits with status code 0.

.Sh FILE STRUCTURE
.Nm
follows a simple structure for including files.
There are two ways a file is inluded.

The shebang symbol
.Pq Sy "#!"
is used as the inclusion operator and will always be included.
.Em NOTE:
If an inclusion operator is used before any text,
the first instance will be ignored as it is seen as a shebang.
If another file needs to be included immediately, preceding it with an empty variable
.Pq Sy "${}"
will allow that.
.Em NOTE:
Inclusions are relative to each file processed.

The environmental inclusion operator
.Pq Sy "#?"
will be included if the environment variable exists.
The environmental inclusion operator will include the file located at the value specified by the environment.
If the value is not specified in the environment, it will be ignored.
.Em NOTE:
Environmental inclusions are relative to the first file processed.

.Nm
also allows variable substitution.
Strings enclosed in
.Sy "${"
and
.Sy "}"
will be replaced with the value specified by the environment.
If the value is not specified in the environment, then it will be replaced with nothing.

.Em WARNING:
There are no checks for recursion.

.Sh AUTHORS
.An Harry N
